spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/metadonnee_db
    username: gallagher
    password: gallagher09
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: gallagher
    password: gallagher09

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework: DEBUG

server:
  port: 8103
