spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/courriers_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: gallagher
    password: gallagher09
    
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: gallagher
    password: gallagher09
  jackson:
    default-property-inclusion: non_null
    stream-write-constraints:
      max-nesting-depth: 500
    serialization:
      indent_output: true
    deserialization:
      fail_on_unknown_properties: false


logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework: DEBUG

app:
  file-storage:
    base-url: http://localhost:8201




server:
  port: 8201
