server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3307/kairos_users_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: gallagher
    password: gallagher09
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: gallagher
    password: gallagher09
  config:
    retry:
      initial-interval: 1000
      max-attempts: 10
      max-interval: 2000
      multiplier: 1.1

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000
  refresh-token:
    expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework: DEBUG